apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: dnU3MmNjZGc=
  CLOUDINARY_KEY: Mjg4ODc2MzQ5NDU4NzQx
  CLOUDINARY_SECRET: SjBBUTBySTI3ZlgtOF9BYURBX2pCcVAyZHhz
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lhbUZuWVdScGMyaHJkVzF3WVhScElpd2lZU0k2SW1OdGRUVjNZWEIwTnpBMGVtWXllbk0zTlRGc1kzUXdPVzhpZlEubHU0cFhBaEpJdEt6c1JSQ3gydnQtUQ==
  DB_URL: bW9uZ29kYitzcnY6Ly9rdW1wYXRpamFnYWRpc2gyMDAxX2RiX3VzZXI6YWRtaW4xMjNAY2x1c3RlcjAucGRocmt0ay5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMCAtbgo=
